language: cpp
matrix:
  include:
  - os: linux
    env: NAME="clang-format"
    dist: trusty
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-6.0
        - ubuntu-toolchain-r-test
        packages:
        - clang-format-6.0
    script: "./.travis/clang-format/script.sh"
  - os: linux
    env: NAME="linux build"
    sudo: required
    dist: trusty
    services: docker
    addons:
      apt:
        packages:
        - p7zip-full
    install: "./.travis/linux/deps.sh"
    script: "./.travis/linux/build.sh"
    after_success: "./.travis/linux/upload.sh"
    cache: ccache
  - os: osx
    env: NAME="macos build"
    sudo: false
    osx_image: xcode10
    install: "./.travis/macos/deps.sh"
    script: "./.travis/macos/build.sh"
    after_success: "./.travis/macos/upload.sh"
    cache: ccache
  - os: linux
    env: NAME="linux build (frozen versions of dependencies)"
    sudo: required
    dist: trusty
    services: docker
    cache: ccache
    script: "./.travis/linux-frozen/build.sh"
  - os: linux
    env: NAME="MinGW build"
    sudo: required
    dist: trusty
    services: docker
    addons:
      apt:
        packages:
        - p7zip-full
    install: "./.travis/linux-mingw/deps.sh"
    script: "./.travis/linux-mingw/build.sh"
    after_success: "./.travis/linux-mingw/upload.sh"
    cache: ccache
before_deploy:
- git config --local user.name "Valentin Vanelslande"
- git config --local user.email "valentinvanelslandeacnl@gmail.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  api_key:
    secure: uUzVCJOueDnBwsP8xMcvGHiJ0ajTRbxectYvKcahEntpmcwEZGDfQIznTFAMS67uTR6WdV2SuD25bR+ZuT+fZr+P6nFNMah4nRkkrnqDDv71aT8Xftam+l9Y3Mvj0dzkdC+RZT3UdsVQkyF+7bcMcHZ0M6wL1773IU4P+w6bwbhpiWMYPWWavyQd3QeQfQyEm0kVmlFNfGiftoUjERvMd4vvMIvJzxnKU77TprJ4wHtwunwLehh+/b7UQufyuGMmlqeGqHG7Jhn+enRgLUXRvu+mz8WIVlLtRLLVzPu5vq0apnkOYHBiIdxSTdPNqIfe6zIr5sHFg1afmkl0zMI3jOICLF0KmJTEGSXTD4BiIc/3m+nh62vY/G0DX84lu0eFDjmsbp05mFUBfrkO3FVaZ1Cd0SRUTXdLGKWhpaU4BmcYPupCYnn1XEFW+4zJUUReNEVQgzfHNErkqS7lQsPMpbUpRxtZsoZGex6YixoV7T4PdHpWKwADOOlz48SsTr23wQ+CUfDMSln3oZlX1ck7ePTNgHeInuCiBmjkk1EHDCrD2iyK26jBnhKNAXZgqwrqYpUuUJMNczMj1wSOt36s5/6czpV5D58d8Rvu/zNVmwMVh2Ym/CkvM7Cujy2yjfvSloYox6noSaCk3ka/t5dWIPDwXsGKHw5oLeR/a/Z+axc=
  file_glob: true
  file: "artifacts/*"
  skip_cleanup: true
  on:
    tags: false
